parameters:
#    main_page.example.class: MainPage\MainPageBundle\Example

services:
#    main_page.example:
#        class: %main_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
